### ISSUE TITLE
Inicio desarrollo sección Aliento de vida

### ISSUE THREAD

**Issue by gamarcano** [ministeriovpi/web#6]
@guillermopinzon280 **Bienvenido**. comenzamos con una sección básica.
Desarrollar la sección de Aliento de vida. Desarrolla los archivos del directorio Aliento.
Cualquier duda, comentario o nota la haces por aquí.

**Comment by gamarcano** [comment]
@guillermopinzon280 clona el repositorio y abre una rama para que vayas desarrollando.

**Comment by gamarcano** [comment]
Cuéntame @guillermopinzon280. La sección de Aliento de Vida esta esperando!

**Comment by guillermopinzon280** [comment]
Buenas noches hermano, sigo avanzando con el diseño de la sección, falta poco...
le envío un avance de lo que llevo

**Comment by guillermopinzon280** [comment]
además... no introdujo el css del programa, por ende, tuve que reacer uno nuevo

**Comment by gamarcano** [comment]
> Buenas noches hermano, sigo avanzando con el diseño de la sección, falta poco...
> le envío un avance de lo que llevo

Vale. crea un ramal y lo publicas en una "page".

**Comment by gamarcano** [comment]
> además... no introdujo el css del programa, por ende, tuve que reacer uno nuevo

Guillermo, el ccs de la plantilla está en el directorio -> **web/assets/css/style.css**
como te comenté, puedes hacer referencia a él pero no debes modificarlo.
Debes referenciarlo si quieres conservar los estilos, **de hecho hay que conservar el estilo. <-- OJO**
